<?php

namespace fucodo\hotwire\turbo\ViewHelpers;

use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractTagBasedViewHelper;

class TurboFrameViewHelper extends AbstractTagBasedViewHelper
{
    /**
     * Name of the tag to be created by this view helper
     *
     * @var string
     * @api
     */
    protected $tagName = 'turbo-frame';

    public function initializeArguments()
    {
        parent::initializeArguments();
        $this->registerTagAttribute('id', 'string', 'the id of the turbo frame', false);
        $this->registerTagAttribute('src', 'string', 'the source for eager loading', false);
        $this->registerArgument('propagateUrl', 'bool', 'Whether the URL should be pushed to browser history', false, false);
    }

    public function render()
    {
        return parent::render(); // TODO: Change the autogenerated stub
    }
}
